-- MySQL Script generated by MySQL Workbench
-- 02/22/15 20:53:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`uploadFileSlice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uploadFileSlice` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fileName` VARCHAR(45) NOT NULL COMMENT '文件名字',
  `fileSize` VARCHAR(10) NOT NULL COMMENT '文件总大小，单位byte',
  `fileType` VARCHAR(5) NOT NULL COMMENT '文件类型（后缀）',
  `fileUrl` VARCHAR(45) NOT NULL,
  `fileNowSize` VARCHAR(10) NOT NULL COMMENT '目前已经上传文件大小(单位byte)',
  `sliceTotal` INT UNSIGNED NOT NULL COMMENT '文件分片总数',
  `fileMd5` CHAR(32) NOT NULL COMMENT '文件MD5',
  `uploadStartTime` CHAR(10) NOT NULL COMMENT '文件上传断点时间（单位秒，要用于过期处理）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '断点上传记录表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
